name: Build Lua Dynamic Library

on:
   push:
    branches:
      - main  # Trigger on push to main branch
   workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: macos-latest  # Use a macOS environment to build the .dylib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        echo "Installing Lua, Lua-lfs and CMake..."
        brew install lua cmake
         brew install lua cmake luarocks
        luarocks install luafilesystem  # Install LuaFileSystem

    - name: Create Build Directory
      run: |
        echo "Creating build directory..."
        mkdir -p build

    - name: Configure CMake
      run: |
        echo "Configuring CMake..."
        cd build
        cmake ..  # CMakeLists.txt is in the parent directory

    - name: Build Dynamic Library
      run: |
        echo "Building the dynamic library..."
        cd build
        cmake --build . --config Release

    - name: Copy Built Library
      run: |
        echo "Copying built library to output directory..."
        mkdir -p output
        cp build/libmylibrary.dylib output/  # Adjusted path for output

    - name: Upload Library
      uses: actions/upload-artifact@v3  # Using the latest stable version
      with:
        name: mylibrary
        path: output/libmylibrary.dylib

    - name: Clean Up
      run: |
        echo "Cleaning up..."
        rm -rf build  # Optionally remove the build directory after the process
