name: Sign and Distribute IPA

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  sign-ipa:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (zsign and other tools)
      - name: Install zsign and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          # Download and install zsign
          curl -L -o zsign https://github.com/zhlynn/zsign/releases/latest/download/zsign_linux_x86_64
          chmod +x zsign
          sudo mv zsign /usr/local/bin/

      # Step 3: Download the IPA file from Filebin
      - name: Download IPA File
        run: |
          curl -L -o DokkanSparking_Release_5.25.3.ipa https://filebin.net/mwoj4adth3toumo1/DokkanSparking_Release_5.25.3.ipa
          ls -lh DokkanSparking_Release_5.25.3.ipa

      # Step 4: Find certificate and provisioning profile
      - name: Locate Certificate and Provisioning Profile
        id: find-files
        run: |
          P12_FILE=$(find Priv -name "*.p12" | head -n 1)
          MOBILEPROVISION_FILE=$(find Priv -name "*.mobileprovision" | head -n 1)
          if [ -z "$P12_FILE" ] || [ -z "$MOBILEPROVISION_FILE" ]; then
            echo "Error: Could not find .p12 or .mobileprovision file in Priv folder"
            exit 1
          fi
          echo "p12_file=$P12_FILE" >> $GITHUB_OUTPUT
          echo "mobileprovision_file=$MOBILEPROVISION_FILE" >> $GITHUB_OUTPUT
          echo "Found .p12: $P12_FILE"
          echo "Found .mobileprovision: $MOBILEPROVISION_FILE"

      # Step 5: Sign the IPA with zsign
      - name: Sign IPA with zsign
        run: |
          zsign -k "${{ steps.find-files.outputs.p12_file }}" \
                -p "1234" \
                -m "${{ steps.find-files.outputs.mobileprovision_file }}" \
                -o signed_DokkanSparking_Release_5.25.3.ipa \
                DokkanSparking_Release_5.25.3.ipa
          if [ ! -f signed_DokkanSparking_Release_5.25.3.ipa ]; then
            echo "Error: Signing failed, signed IPA not found"
            exit 1
          fi
          echo "Signed IPA created: signed_DokkanSparking_Release_5.25.3.ipa"

      # Step 6: Create manifest for OTA installation
      - name: Create Manifest for OTA Installation
        run: |
          # Install PlistBuddy for bundle ID extraction
          sudo apt-get install -y libplist-utils
          /usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" "${{ steps.find-files.outputs.mobileprovision_file }}" > temp_bundle_id.txt
          BUNDLE_ID=$(cat temp_bundle_id.txt | cut -d'.' -f2-)
          echo "Bundle ID: $BUNDLE_ID"
          
          # Create manifest.plist
          cat << EOF > manifest.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>items</key>
            <array>
              <dict>
                <key>assets</key>
                <array>
                  <dict>
                    <key>kind</key>
                    <string>software-package</string>
                    <key>url</key>
                    <string>https://github.com/${{ github.repository }}/releases/latest/download/signed_DokkanSparking_Release_5.25.3.ipa</string>
                  </dict>
                </array>
                <key>metadata</key>
                <dict>
                  <key>bundle-identifier</key>
                  <string>$BUNDLE_ID</string>
                  <key>bundle-version</key>
                  <string>5.25.3</string>
                  <key>kind</key>
                  <string>software</string>
                  <key>title</key>
                  <string>DokkanSparking</string>
                </dict>
              </dict>
            </array>
          </dict>
          </plist>
          EOF
          cat manifest.plist

      # Step 7: Upload signed IPA and manifest to GitHub Releases
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            signed_DokkanSparking_Release_5.25.3.ipa
            manifest.plist
          tag_name: v${{ github.run_id }}
          name: Signed IPA Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Generate and output OTA installation link
      - name: Output OTA Installation Link
        run: |
          INSTALL_LINK="itms-services://?action=download-manifest&url=https://github.com/${{ github.repository }}/releases/download/v${{ github.run_id }}/manifest.plist"
          echo "OTA Installation Link: $INSTALL_LINK"
          echo "Copy and open this link on your iOS device to install the app."
          echo "install_link=$INSTALL_LINK" >> $GITHUB_OUTPUT